# Christmas special

Today we are going to program a Christmas-special. However, this is still an opportunity to learn something new. We will start offloading settings into a separate file.

## Christmas tree
Let us start our Christmas decoration with a Christmas tree. You can download [the one I've found](material/pine-tree.png) (created by [isaiah658](https://openclipart.org/artist/isaiah658)) or find an image that you like. Create your basic PsychoPy code to create a window, an [ImageStim](https://psychopy.org/api/visual/imagestim.html#psychopy.visual.ImageStim) with a tree, draw it and wait for any key press.

::: {.rmdnote .program}
Put your code into `code01.py`.
:::

## Christmas tree decoration
For the decoration, let us use [Circle](https://psychopy.org/api/visual/circle.html#psychopy.visual.circle.Circle) objects of various sizes and color. 

## Settings file formats {#settings-files}
So far, we either hard-coded specific values or defined them as constants (a better of these two approaches). However, this means that if you want to run your game with different settings, you need to modify the program itself. And if you want to have two versions of the game (two experimental conditions), you would need to have two programs with all the problems of maintaining virtually identical code in several places at once.

A better approach is to have separate files with settings, so you can keep the code constant and alter specific parameters by specifying which settings file the program should use. This is helpful even you plan to have a single set of setting as it separates code from constants, puts the latter all in one place and makes easier to edit and check them. There are multiple formats for settings files: XML, INI, JSON, YAML, etc. I will tell you about the first three, but we will use YAML as our main format today^[This is a question of taste. I like YAML for whatever subjective reasons, but you are free to use any format you like. As you will see, this makes little difference for Python code itself.].

### XML
[XML](https://en.wikipedia.org/wiki/XML) --- an Extensible Markup Language --- looks similar to HTML (HyperText Markup Language). Experiments designed using PsychoPy Builder interface are stored using XML files but with [.psyexp extension](https://www.psychopy.org/psyexp.html). A settings file for Guitar Hero in XML could look like this
```XML
<Target>
  <width>0.4</width>
  <height>0.1</height>
  <locations>
    <location>-0.5</location>
    <location>0</location>
    <location>0.5</location>
  </locations>
</Target>
```


The advantage of XML is that it is very flexible yet structured and you can use [native Python interface](https://docs.python.org/3/library/xml.html) to work with them. However, XML is not easy for humans to read, it is overpowered for our purposes of having  a simple set of unique constants and its power means that using it is fairly cumbersome.

```python
from xml.dom import minidom
settings = minidom.parse('test.xml')
settings.getElementsByTagName("target")[0].getElementsByTagName("width")[0].firstChild.data # this will give you string "0.4"
```

### INI
This is a format with a structure similar to that found in MS Windows INI files.
```ini
[Target]
width = 0.4
height = 0.1
locations = -0.5, 0, 0.5
```

As you can see it is easier to read and Python has a special [configparser](https://docs.python.org/3/library/configparser.html) library to work with them. The object you get is, effectively, a dictionary with additional methods and attributes. Note, however, that `ConfigParser` does not try to guess the type of data, so all values are stored as _strings_ and it is your job to convert them to whatever type you need, e.g. integer, list, etc.

```python
import configparser
settings = configparser.ConfigParser()
settings.read('settings.ini')
settings["Target"]["width"] # this will give you a string '0.4'
```

### JSON{#json}
[JSON](https://en.wikipedia.org/wiki/JSON) (JavaScript Object Notation) is a popular format for web applications that use it to exchange data between server and client. 
```json
{
  "Target": {
    "width": 0.4,
    "height": 0.1,
    "locations": [-0.5, 0, 0.5]
  }
}
```

You can parse any _string_ with JSON format into a dictionary in Python using [json](https://docs.python.org/3/library/json.html) module. Its advantage over INI files is that JSON explicitly specifies data type, so it converts it automatically. Note that unlike configparse, json module does not work with files direction, so you need to open it manually.
```python
import json
with open('settings.json') as json_file:
    settings = json.load(json_file)
    
settings["Target"]["width"] # this will give a float number 0.4
```

### YAML{#yaml}
[YAML](https://en.wikipedia.org/wiki/YAML) (YAML Ain't Markup Language, rhymes with camel) is very similar to JSON but its config files are more human-readable. It has fewer special symbols and brackets but, as in Python, you must watch the indentations as they determine the hierarchy.
```yaml
Target:
  width : 0.4
  height : 0.1
  locations : [-0.5, 0, 0.5]
```

You will need to install a third-party library [pyyaml](https://pyyaml.org/) to work with YAML files. Otherwise, you get the same dictionary as for the JSON
```python
import yaml
with open("settings.yaml") as yaml_stream:
    settings = yaml.load(yaml_stream)
    
settings["Target"]["width"] # this will give a float number 0.4
```
